default: &default
  adapter: postgresql
  encoding: unicode
  host: {{ database_hostname }}
  pool: 5
  schema_search_path: "public,shared_extensions"
  username: {{ database_user}}
  password: {{ database_password }}

{{ env }}:
  <<: *default
  database: {{ database_name }}
